name: Update README for wakaTime

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */24 * * *'

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: Updated README with WakaTime
          SHOW_TITLE: true
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          TIME_RANGE: last_6_months
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          LANG_COUNT: 7
